In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"P:\AI\Project_Default\data\raw\accepted_2007_to_2018Q4_xl.csv")

C:\Users\yaswa\AppData\Local\Temp\ipykernel_21560\902509769.py:1: DtypeWarning: Columns (0: id, 1: desc, 2: next_pymnt_d, 3: verification_status_joint, 4: sec_app_earliest_cr_line, 5: hardship_type, 6: hardship_reason, 7: hardship_status, 8: hardship_start_date, 9: hardship_end_date, 10: payment_plan_start_date, 11: hardship_loan_status, 12: debt_settlement_flag_date, 13: settlement_status, 14: settlement_date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"P:\AI\Project_Default\data\raw\accepted_2007_to_2018Q4_xl.csv")

In [3]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(2260701, 151)

In [5]:
# Create a summary dataframe of your columns
df_info = pd.DataFrame({
    'Column Name': df.columns,
    'Data Type': df.dtypes.values,
    'Missing Values': df.isnull().sum().values,
    'Percentage Missing': (df.isnull().sum().values / len(df)) * 100
})

# Display the whole list
df_info.sort_values(by='Percentage Missing', ascending=False)

,Column Name,Data Type,Missing Values,Percentage Missing
1,member_id,float64,2260701,100.000000
140,orig_projected_additional_accrued_interest,float64,2252050,99.617331
130,hardship_reason,str,2249784,99.517097
141,hardship_payoff_balance_amount,float64,2249784,99.517097
142,hardship_last_payment_amount,float64,2249784,99.517097
...,...,...,...,...
43,total_rec_int,float64,33,0.001460
143,disbursement_method,str,33,0.001460
128,hardship_flag,str,33,0.001460
144,debt_settlement_flag,str,33,0.001460
0,id,object,0,0.000000

In [7]:
df['loan_status'].value_counts()

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64